spring:
  datasource:
    url: jdbc:h2:mem:sdw2023   # Banco de dados H2 em memória
    username: sdw2023
    password:
  jpa:
    show-sql: true              # Exibe as queries SQL no console
    open-in-view: false
    hibernate:
      ddl-auto: create          # Cria o schema no startup (pode ser validate, update, create, create-drop)
    properties:
      hibernate:
        format_sql: true        # Formata o SQL exibido no console
  h2:
    console:
      enabled: true             # Ativa o console web do H2
      path: /h2-console         # Caminho de acesso no navegador
      settings:
        trace: false
        web-allow-others: false # Apenas localhost pode acessar
